services:
  server:
    env_file:
      - .env
    build:
      context: ./
    environment:
      MISTRAL_API_KEY: "${MISTRAL_API_KEY}"
      DATABASE_URL: "${DATABASE}"
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./travelguide
          ignore:
            - node_modules/
            - .svelte-kit/